### ISSUE TITLE
Resumption not working

### ISSUE THREAD

**Issue by dragonito** [naoned/OaiPmhServerBundle#3]
Hi there,

I tried the resumption feature. But it shows me the whole 250 records instead of 50 a time.

My url parameters looks like this:

`?verb=ListRecords&metadataPrefix=oai_dc&from=2010-01-01%2000:00:00&until=2016-10-31%2012:00:00`

The getRecords methods, gets the whole data from this timerange.

I also added `count_per_load: 50` to config.yml.

How does resumption should work?

Cu

Robin

**Comment by dragonito** [comment]
Update to dev-master resolved it. Now it adds 50 records. Perhaps you could give me an example url how to get the next 50 records. I tried something like this:

`?verb=ListRecords&metadataPrefix=oai_dc&resumptionToken=XXXXXXXXX`

**Comment by vbeauvivre** [comment]
You can test it here :

http://odysseo.generiques.org/oaipmh/repository/?metadataPrefix=oai_dc&verb=ListRecords
Pick up resumptionToken from footer, then use it like that : 
http://odysseo.generiques.org/oaipmh/repository/?verb=ListRecords&resumptionToken=[XXXXTOKENXXXXX]

It is required that metadata prefix is not requested (it cannot be different from 1st request). See https://www.openarchives.org/OAI/openarchivesprotocol.html#ListRecords

**Comment by dragonito** [comment]
Thanks for your answer!

I tried it, but on my testingserver it won´t work. Its because of the $cacheData['verb'], it is not defined:

`<error code="unknownError">Notice: Undefined index: verb</error>`

If i remove the check in getSearchParams of the [ruler](https://github.com/naoned/OaiPmhServerBundle/blob/master/OaiPmh/OaiPmhRuler.php#L49):

`$cacheData['verb'] != $queryParams['verb']`

It works great.

Is it possible the the verb won´t saved in getResumption-method? Or do you thing something with my provider isn´t right?

**Comment by vbeauvivre** [comment]
The verb is required, even on resupmtion.

**Comment by dragonito** [comment]
I added the verb to the request, its not beeing saved i think
